"""initial schema

Revision ID: 510e180baf1e
Revises: 
Create Date: 2025-07-09 16:42:33.957554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510e180baf1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parameter_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=64), nullable=False),
    sa.Column('sheet_name', sa.String(length=64), nullable=False),
    sa.Column('parameter_name', sa.String(length=64), nullable=False),
    sa.Column('range_value', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('sampling_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('range_value', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['report_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('equipment')
    op.drop_table('user')
    op.drop_table('report')
    op.drop_table('department')
    op.drop_table('parameter_range')
    op.drop_table('report_section')
    op.drop_table('report_parameter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_parameter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('section_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('range_value', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['report_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_section',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_id', sa.INTEGER(), nullable=True),
    sa.Column('sheet_name', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameter_range',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('sheet_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('parameter_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('range_value', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.Column('sampling_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('equipment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('report_parameters')
    op.drop_table('report_sections')
    op.drop_table('reports')
    op.drop_table('users')
    op.drop_table('equipments')
    op.drop_table('parameter_ranges')
    op.drop_table('departments')
    # ### end Alembic commands ###
